version: 2.1

executors:
  private:
    docker:
      - image: kelvintaywl/cimg-node-18:root
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
  public:
    docker:
      - image: cimg/python:3.9
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
  private-pat:
    docker:
      - image: kelvintaywl/cimg-node-18:root
        auth:
          username: $DOCKERHUB_USERNAME
          # using personal access token instead
          password: $DOCKERHUB_PAT
  public-pat:
    docker:
      - image: cimg/python:3.9
        auth:
          username: $DOCKERHUB_USERNAME
          # using personal access token instead
          password: $DOCKERHUB_PAT
jobs:
  test:
    parameters:
      exec:
        type: executor
    executor: << parameters.exec >>
    steps:
      - run: echo done

workflows:
  main:
    jobs:
      - test:
          matrix:
            parameters:
              exec:
                - private
                - public
                - private-pat
                - public-pat
