version: 2.1

jobs:
  install:
    docker:
      - image: cimg/ruby:2.6.10
    resource_class: medium
    steps:
      - run: ruby --version
      - run: bundler --version

workflows:
  ruby:
    jobs:
      - install
