version: 2.1

jobs:
  diskspace:
    parameters:
      size:
        type: string
    docker:
      - image: cimg/openjdk:11.0
    resource_class: << parameters.size >>
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - run: df -h

workflows:
  main:
    jobs:
      - diskspace:
          matrix:
            parameters:
              size:
                - medium
                - large
