version: 2.1

jobs:
  build:
    docker:
      # private image on Docker Hub
      - image: docker.io/kelvintaywl/cimg-node-18:circleci
        auth:
          username: kelvintaywl
          password: $DOCKERHUB_PAT
           
    resource_class: kelvintaywl-cci/cntr-runner-eks-ap-south-1
    steps:
      - checkout
      - run: echo "Hi I'm on Runners!"

workflows:
  build-workflow:
    jobs:
      - build
