version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2021.11
    resource_class: kelvintaywl-cci/cntr-runner-eks-ap-south-1
    steps:
      - checkout
      - run: echo "Hi I'm on Runners!"

workflows:
  build-workflow:
    jobs:
      - build
