version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
      - image: opensearchproject/opensearch:1.3.2
        environment:
          - cluster.name=opensearch-cluster
          - node.name=opensearch
          - discovery.seed_hosts=opensearch
          - discovery.type=single-node
          - bootstrap.memory_lock=true
          - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
          - http.cors.enabled=true
          - http.cors.allow-origin=*
          - http.cors.allow-headers=Authorization,Content-Type
          - http.cors.allow-credentials=true
          - DISABLE_INSTALL_DEMO_CONFIG=true
          - DISABLE_SECURITY_PLUGIN=true
          # See https://opensearch.org/docs/latest/install-and-configure/configuring-opensearch/logs/#application-logs
          - logger.org.opensearch.discovery=DEBUG
    resource_class: medium
    parallelism: 1
    steps:
      - run:
          name: wait for OpenSearch server to be up
          command: |
            N=30
            while [ $N -gt 0 ]
            do
              if $(curl -s -f http://localhost:9200 > /dev/null); then
                echo "Pinged OpenSearch!"
                exit 0
              fi
              echo "OpenSearch is not reachable; retrying"
              N=$(( $N - 1 ))
              sleep 1
            done
            exit 1
      - run:
          name: disable Performance Analyzer
          command: |
            # https://opensearch.org/docs/latest/monitoring-your-cluster/pa/index/#disable-performance-analyzer
            curl -XPOST localhost:9200/_plugins/_performanceanalyzer/rca/cluster/config -H 'Content-Type: application/json' -d '{"enabled": false}'
      - run: echo done
