version: 2.1

orbs:
  php: circleci/php@1.1.0

executors:
  linux:
    machine:
      image: ubuntu-2204:2023.02.1
  dock:
    docker:
      - image: rhodeswebdev/cci-drupal-percy:v0.15

commands:
  check-deps:
    steps:
      - run: php --version
      - run: composer --version

jobs:
  php-check-machine:
    executor: linux
    steps:
      - run: sudo apt -y update && sudo apt -y install php php-xml php-mbstring php-gd php-curl
      - php/install-composer
      - check-deps
  php-check-docker:
    executor: dock
    steps:
      - check-deps


workflows:
  main:
    jobs:
      - php-check-machine
      - php-check-docker
