version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
      - image: opensearchproject/opensearch:1.3.2
        environment:
          - cluster.name=opensearch-cluster
          - node.name=opensearch
          - discovery.seed_hosts=opensearch
          - discovery.type=single-node
          - bootstrap.memory_lock=true
          - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
          - http.cors.enabled=true
          - http.cors.allow-origin=*
          - http.cors.allow-headers=Authorization,Content-Type
          - http.cors.allow-credentials=true
          - DISABLE_INSTALL_DEMO_CONFIG=true
          - DISABLE_SECURITY_PLUGIN=true
          # See https://opensearch.org/docs/latest/install-and-configure/configuring-opensearch/logs/#application-logs
          - logger.org.opensearch.discovery=DEBUG
    resource_class: medium
    parallelism: 11
    steps:
      - run: sleep 30
