version: 2.1

executors:
  linux:
    machine:
      image: ubuntu-2204:2023.02.1
  dock:
    docker:
      - image: rhodeswebdev/cci-drupal-percy:v0.15

jobs:
  php-check:
    parameters:
      exec:
        type: executor
    executor: << parameters.exec >>
    steps:
      - when:
          condition:
            equal: ["linux", << parameters.exec >>]
          steps:
            - run: sudo apt update && sudo apt install php php-xml php-mbstring php-gd php-curl
      - run: php --version
      - run: composer --version

workflows:
  main:
    jobs:
      - php-check:
          matrix:
            parameters:
              exec:
                - linux
                - dock
