version: 2.1

parameters:
  jdk:
    type: integer
    default: &jdk_default_version 11

executors:
  jdk:
    parameters:
      version:
        type: integer
        default: *jdk_default_version
    docker:
      - image: comg/openjdk:<<parameters.version>>.0-node
    resource_class: small
jobs:
  test0:
    executor:
      name: jdk
    steps:
      - run: echo test0
  test1:
    executor:
      name: jdk
      version: 10
    steps:
      - run: |
         echo test1

workflows:
  main:
    jobs:
      - test0
      - test1
