version: 2.1

jobs:
  sample:
    docker:
      - image: cimg/aws:2023.06
    resource_class: medium
    steps:
      - setup_remote_docker:
          version: '20.10.18'
      - run: docker info
      - run:
          name: run Docker container (background)
          background: true
          command: |
            docker pull kelvintaywl/fancy-nginx

            # NOTE: our container needs to remain running,
            # in order for us to docker cp or docker exec
            docker run --name nginx -p 5050:80 kelvintaywl/fancy-nginx
      - run:
          name: wait for Docker container
          command: |
            dockerize -wait http://127.0.0.1:5050 -timeout 10s
      - run:
          name: Inspect files
          command: |
            # the container has HTML files under /usr/share/nginx/html folder
            # See https://github.com/kelvintaywl/whale-of-a-time/blob/master/Dockerfile
            docker exec nginx ls /usr/share/nginx/html/

            docker cp nginx:/usr/share/nginx/html/index.html ./downloaded.html

            cat ./downloaded.html

workflows:
  main:
    jobs:
      - sample
