version: 2.1

jobs:
  update:
    parameters:
      img:
        type: string
    docker:
      - image: << parameters.img >>
    steps:
      - run: sudo apt-get update

workflows:
  aptgetupdate:
    jobs:
      - update:
          matrix:
            parameters:
              img:
                - circleci/node:14.8.0
                - cimg/node:14.8.0
