version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
      - image: opensearchproject/opensearch:1.3.2
        environment:
          - cluster.name=opensearch-cluster
          - node.name=opensearch
          - discovery.seed_hosts=opensearch
          - discovery.type=single-node
          - bootstrap.memory_lock=true
          - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
          - http.cors.enabled=true
          - http.cors.allow-origin=*
          - http.cors.allow-headers=Authorization,Content-Type
          - http.cors.allow-credentials=true
          - DISABLE_INSTALL_DEMO_CONFIG=true
          - DISABLE_SECURITY_PLUGIN=true
          # See https://opensearch.org/docs/latest/install-and-configure/configuring-opensearch/logs/#application-logs
          - logger.org.opensearch.discovery=DEBUG
    resource_class: medium
    parallelism: 1
    steps:
      - run:
          name: disable Performance Analyzer
          command: |
            # TODO: improve deterministic check that OpenSearch server is ready
            sleep 30
            # curl -X POST localhost:9200/_plugins/_performanceanalyzer/cluster/config -H 'Content-Type: application/json' -d '{"enabled": false}'
            # https://opensearch.org/docs/latest/monitoring-your-cluster/pa/index/#disable-performance-analyzer
            curl -XPOST localhost:9200/_plugins/_performanceanalyzer/rca/cluster/config -H 'Content-Type: application/json' -d '{"enabled": false}'
      - run: sleep 30
