version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@3.1.0

jobs:
  install:
    docker:
      - image: gcr.io/google.com/cloudsdktool/google-cloud-cli:debian_component_based
    resource_class: medium
    steps:
      - gcp/install:
          version: '440.0.0'

workflows:
  gcp-cli:
    jobs:
      - install
