version: 2.1

executors:
  azul-openjdk-21:
    docker:
      - image: docker.io/azul/zulu-openjdk:21
    resource_class: large

jobs:
  azul:
    executor: azul-openjdk-21
    steps:
      - run: whoami
      - run: printenv PATH

workflows:
  main:
    jobs:
      - azul
