version: 2.1

jobs:
  build:
    parameters:
      docker-version:
        type: string
    resource_class: medium
    docker:
      - image: google/cloud-sdk
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
          version: << parameters.docker-version >>
      - checkout
      - run: docker build -t test .

workflows:
  docker:
    jobs:
      - build:
          matrix:
            parameters:
              docker-version:
                - "20.10.2"
                - "20.10.10"
                - "20.10.18"
                - "19.03.13"
