version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
      - image: opensearchproject/opensearch:1.3.2
        environment:
          - cluster.name=opensearch-cluster
          - node.name=opensearch
          - discovery.seed_hosts=opensearch
          - discovery.type=single-node
          - bootstrap.memory_lock=true
          - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
          - http.cors.enabled=true
          - http.cors.allow-origin=*
          - http.cors.allow-headers=Authorization,Content-Type
          - http.cors.allow-credentials=true
          - DISABLE_INSTALL_DEMO_CONFIG=true
          - DISABLE_SECURITY_PLUGIN=true
          # See https://opensearch.org/docs/latest/install-and-configure/configuring-opensearch/logs/#application-logs
          - logger.org.opensearch.discovery=DEBUG
      - image: cimg/mysql:5.7.36
        environment:
          TZ: America/Los_Angeles
          MYSQL_DATABASE: opensearch_test
          MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_USER: opensearch
          MYSQL_PASSWORD: openSearchR0X
    resource_class: medium
    parallelism: 4
    steps:
      - run:
          name: wait for MySQL server to be up (2 mins)
          command: |
            dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: wait for OpenSearch server to be up (2 mins)
          command: |
            dockerize -wait tcp://127.0.0.1:9200 -timeout 120s
      - run:
          name: disable Performance Analyzer
          command: |
            # https://opensearch.org/docs/latest/monitoring-your-cluster/pa/index/#disable-performance-analyzer
            curl -X POST localhost:9200/_plugins/_performanceanalyzer/rca/cluster/config -H 'Content-Type: application/json' -d '{"enabled": false}'
      - run: echo done
