version: 2.1

parameters:
  jdk:
    type: integer
    default: &jdk_default_version 11

jobs:
  test0:
    parameters:
      version:
        type: integer
        default: *jdk_default_version
    docker:
      - image: cimg/openjdk:<<parameters.version>>.0-node
    resource_class: small
    steps:
      - run: echo test0
  test1:
    parameters:
      version:
        type: integer
        default: *jdk_default_version
    docker:
      - image: cimg/openjdk:<<parameters.version>>
    resource_class: small
    steps:
      - run: |
         echo test1

workflows:
  main:
    jobs:
      - test0
      - test1
