version: 2.1

jobs:
  inspect:
    docker:
      - image: cimg/ruby:3.1.4-browsers
    resource_class: small
    steps:
      - run: which chromedriver
      - run: which msedgedriver

workflows:
  ruby:
    jobs:
      - inspect
