version: 2.1

executors:
  base:
    docker:
      # private image on DockerHub
      - image: kelvintaywl/cimg-node-18:python
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
      - image: cimg/redis:6.2.6
    # container runner
    resource_class: kelvintaywl-cci/cntr-runner-eks-ap-south-1
jobs:
  test:
    parameters:
      exec:
        type: executor
        default: base
    executor: << parameters.exec >>
    steps:
      - run: echo done

workflows:
  main:
    jobs:
      - test:
          context:
            - dockerhub
