version: 2.1

executors:
  base:
    docker:
      # private image on DockerHub
      - image: kelvintaywl/cimg-node-18:root
      - image: cimg/redis
jobs:
  test:
    parameters:
      exec:
        type: executor
        default: base
    executor: << parameters.exec >>
    steps:
      - run: echo done

workflows:
  main:
    jobs:
      - test:
          context:
            - dockerhub
